config/routes.rb
Horsey::Application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'application#game'

    post 'mail', to: 'application#send_mail'
    get 'mail', to: 'application#mail'

    post 'save', to: 'application#save_score'
    post 'place', to: 'application#get_place'
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  default_scope { order('value DESC, updated_at DESC') }

  def self.get_place score
    record = where('value > ?', score).last
    index  = all.index record
    index ? index + 2 : 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  def send_mail
    UserMailer.new_years_mail(params[:mail]).deliver
    redirect_to :back, notice: 'Письма отправлены.'
  end

  def save_score
    score = Score.create! name: params[:name], value: params[:value].to_i
    render partial: 'shared/top', locals: { current: score }
  end

  def get_place
    place = Score.get_place params[:score].to_i
    render text: place
  end

  protected

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    I18n.locale == I18n.default_locale ? { locale: nil } : { locale: I18n.locale }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/game.haml
- content_for :javascript do
  = javascript_include_tag :game
  %script{:src => "//vk.com/js/api/openapi.js?105"}
  :javascript
    // Twitter
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
    // Facebook
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=578823792198061";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    // VK
    VK.init({apiId: 4064171, onlyWidgets: true});
    VK.Widgets.Like("vk_like", {type: "mini", height: 20});

#container
  #start
    .frame
      .start-screen
        %h1= t('root.title')
        %h2= t('root.description')
        = image_tag "velogame.png", :alt => ""
        %button.play= t('root.play')
        %button.top TOP 10
        .buttons
          .facebook
            #fb-root
            .fb-like{:data => {:href => "http://velogame.pro", :layout => "button_count", :action => "like", :"show-faces" => "false", :share => "false"}}
          .vkontakte
            #vk_like
          .twitter
            %a.twitter-share-button{:href => "https://twitter.com/share", :data => {:url => "http://velogame.pro", :text => "Я гоняю на коне! #velogame", :lang => "en"}}

        .footer
          &copy;
          %a{:href => "http://molinos.ru", :target => "_blank"} Molinos.Ru
      .top-screen
        %h2 TOP 10
        .table
          = render partial: 'shared/top'
        %button.back= t('top10.back')
  #keys
    .frame
      %i
        = t('game.use')
        %span.desktop= t('game.keys')
        %span.mobile= t('game.buttons')
      %span.arrow.up
      %span.arrow.down
  #game
    .frame
      #main
      #pause{ title: t('game.pause') }
      #lives
        .life
        .life
        .life
      #score 0
      #controls
        %button.up
        %button.down
      .sun
      .noise
  #gameover
    .frame
      .prelim-score
        %h2= t('game.gameover')
        .result
          = t('game.score')
          %span
        .place
          = t('game.rating')
          %span
        %form.score
          %label= t('game.register')
          %input{:maxlength => "20"}
          %button.save= t('game.famous')
        %button.play= t('game.again')
        .share
          %span= t('game.share')
          -#%a.facebook{:href => "http://www.facebook.com/sharer.php?u=http://velogame.pro&t=Title", :target =>"_blank"}
          %a.facebook{:href => "http://www.facebook.com/sharer.php?s=100&p[title]=Я%20гоняю%20на%20коне!&p[url]=http://velogame.pro&p[summary]=Велоконь:%20игра%20о%20жизни,%20смерти%20и%20коне%20%23velogame&p[images][0]=http://velogame.pro/i/share.png", :target =>"_blank"}
          -#%a.vkontakte{:href => "http://vkontakte.ru/share.php?url=http://velogame.pro", :target =>"_blank"}
          %a.vkontakte{:href => "http://vkontakte.ru/share.php?title=Я%20гоняю%20на%20коне!&url=http://velogame.pro&description=Велоконь:%20игра%20о%20жизни,%20смерти%20и%20коне%20%23velogame&image=http://velogame.pro/i/share-vk.png", :target =>"_blank"}
          %a.twitter{:href => "http://twitter.com/share?text=Я%20гоняю%20на%20коне!%20%23velogame&url=http://velogame.pro", :target =>"_blank"}
        .footer
          &copy;
          %a{:href => "http://molinos.ru", :target => "_blank"} Molinos.Ru
      .top
        %h2 TOP 10
        .table
        %button.play= t('game.again')
        .share
          %span= t('game.share')
          -#%a.facebook{:href => "http://www.facebook.com/sharer.php?u=http://velogame.pro&t=Title", :target =>"_blank"}
          %a.facebook{:href => "http://www.facebook.com/sharer.php?s=100&p[title]=Я%20гоняю%20на%20коне!&p[url]=http://velogame.pro&p[summary]=Велоконь:%20игра%20о%20жизни,%20смерти%20и%20коне%20%23velogame&p[images][0]=http://velogame.pro/i/share.png", :target =>"_blank"}
          -#%a.vkontakte{:href => "http://vkontakte.ru/share.php?url=http://velogame.pro", :target =>"_blank"}
          %a.vkontakte{:href => "http://vkontakte.ru/share.php?title=Я%20гоняю%20на%20коне!&url=http://velogame.pro&description=Велоконь:%20игра%20о%20жизни,%20смерти%20и%20коне%20%23velogame&image=http://velogame.pro/i/share-vk.png", :target =>"_blank"}
          %a.twitter{:href => "http://twitter.com/share?text=Я%20гоняю%20на%20коне!%20%23velogame&url=http://velogame.pro", :target =>"_blank"}
-#
  %audio#hit{:preload => "auto"}
    %source{:src => "/sounds/fall.ogg"}
    %source{:src => "/sounds/fall.mp3"}
#activity

app/views/application/horsey.haml
#container
  #start
    .frame
      %h1 Велоконь
      %button.play Играть
      %button.top TOP 15
  #game
    .frame
      #main
      -#
        #pause
      #lives
        .life
        .life
        .life
      #score 0
      #controls
        %button.up
        %button.down
      .sun
      .noise
  #gameover
    .frame
      %h2 Приехали…
      .result
        Результат:
        %span 2560
      .place
        Место
        %span 12
      -# Минимальный функционал — простая форма для ввода имени.
      %form
        .field
          %label Представтесь
          %input
        .submit
          %button Прославиться
      -# Желательно — авторизация через фейсбуки.
      -# Тогда форма для ввода имени не нужна? Можно обсудить.
      %ul
        %li
          %a.vk{:href => "#"} ВКонтакте
        %li
          %a.fb{:href => "#"} Фейсбук
      -# По макету после авторизации здесь выводится таблица. Можно обсудить.
      .top
        %table
          %tr
            %td 11
            %td Александр Друзь
            %td 1&thinsp;282
          %tr.result
            %td 12
            %td Константин Жеребцов
            %td 1&thinsp;154
          %tr
            %td 13
            %td Алексей Ёжиков
            %td 420
      %button.play Ещё разок
#activity

app/views/application/index.haml
.pumping-up
  .frame
    .intro
      %p
        %span Немного терпения,
        идет подготовка к запуску...
      %p.nb
        %span 25 декабря здесь будет игра
        о жизни,
        %s смерти
        и коне
      = image_tag "pumping-up.png", :alt => ""
    .buttons
      .facebook
        #fb-root
        .fb-like{:data => {:href => "http://velogame.molinos.ru", :layout => "button_count", :action => "like", :"show-faces" => "false", :share => "false"}}
      .vkontakte
        #vk_like
      .twitter
        %a.twitter-share-button{:href => "https://twitter.com/share", :data => {:url => "http://velogame.molinos.ru", :text => "Игра о жизни, смерти и коне", :lang => "en"}}
    .footer
      &copy;
      %a{:href => "http://molinos.ru"} Molinos.Ru

- content_for :javascript do
  %script{:src => "//vk.com/js/api/openapi.js?105"}
  :javascript
    // Twitter
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
    // Facebook
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=457100904321833";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    // VK
    VK.init({apiId: 4064171, onlyWidgets: true});
    VK.Widgets.Like("vk_like", {type: "mini", height: 20});

app/views/application/mail.haml
.mail
  = form_for :mail, url: mail_path, html: { id: 'mail' } do |f|
    .field
      = f.label :to, 'Адрес'
      = f.text_field :to
    .field
      = f.label :name, 'От кого (имя)'
      = f.text_field :name, value: 'Molinos'
    .field
      = f.label :email, 'От кого (email)'
      = f.text_field :email, value: 'studio@molinos.ru'
    .field
      = f.label :subject, 'Тема письма'
      = f.text_field :subject, value: 'С Новым Годом!'
    .submit
      = f.submit 'Отправить'

app/views/layouts/application.haml
!!! 5
%html#no-js{:lang => "ru"}
  %head
    = csrf_meta_tag
    %meta{:charset => "utf-8"}
    %title= @meta_title || t('root.title')
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "keywords"}
    %meta{:name => "viewport", :content => "width=1280, user-scalable=no"}
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}
    %link{:href => "http://fonts.googleapis.com/css?family=Bad+Script&subset=latin,cyrillic", :rel => "stylesheet"}
    = stylesheet_link_tag :app, :media => "all"

    %meta{:property => "og:title", :content => t('meta.title')}
    %meta{:property => "og:description", :content => "#{t('meta.description')} #velogame"}
    %meta{:property => "vk:description", :content => "#{t('meta.description')} #velogame"}
    %meta{:property => "og:url", :content => "http://velogame.pro"}
    %meta{:property => "vk:url", :content => "http://velogame.pro?v3"}
    %meta{:property => "og:image", :content => "http://velogame.pro/i/share.png"}
    %meta{:property => "vk:image", :content => "http://velogame.pro/i/share-vk.png"}
    %meta{:name => "title", :content => t('meta.title')}
    %meta{:name => "description", :content => "#{t('meta.description')} #velogame"}
    %link{:rel => "image_src", :href => "http://velogame.pro/i/share.png"}
    %meta{:property => "og:type", :content => "website"}
    %meta{:property => "fb:admins", :content => "647725985"}
    %meta{:property => "fb:app_id", :content => "578823792198061"}

  %body
    - if flash[:notice]
      .message= flash[:notice]

    = yield

    = javascript_include_tag :app
    = yield :javascript

    = render 'shared/analytics'

app/views/shared/_analytics.haml
- if Rails.env == 'production'
  :javascript
    // GA
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-46469350-1', 'velogame.pro');
    ga('send', 'pageview');
    // YM
    (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
        try {
          w.yaCounter23427940 = new Ya.Metrika({id:23427940,
            webvisor:true,
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true});
        } catch(e) { }
      });
      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
      if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
  %noscript
    %div
      %img{:src => "//mc.yandex.ru/watch/23427940", :style => "position: absolute; left: -9999px;", :alt => ""}

app/views/shared/_top.haml
%table
  - Score.limit(10).each_with_index do |score, i|
    %tr{ class: defined?(current) && current == score && 'current' }
      %td= i + 1
      %td= score.name
      %td= number_with_delimiter score.value

- if defined?(current) and index = Score.all.index(current) + 1 and index > 10
  .current
    %span.position= index
    %span.name= current.name
    %span.score= number_with_delimiter current.value